#!/bin/bash
# Author: Igor Shcheglakov (i.shcheglako@samsung.com)

OPTION_IP_ADDR=
OPTION_PKG_DIR=
OPTION_PKG_VERSION=

declare -a OPTION_RPMS

function usage()
{
  echo "Usage: `basename $0` [-i=<addr>] [-v=<version>] [-d=<dir>] [vnc|rdp|knox]"
}

function parse_cmd()
{
  for ARG in "$@"; do
    case "$ARG" in
      -i=*)
        OPTION_IP_ADDR=${ARG#*=}
        ;;
      -d=*)
        OPTION_PKG_DIR=${ARG#*=}
	;;
      -v=*)
        OPTION_PKG_VERSION=${ARG#*=}
        ;;
      vnc)
        OPTION_RPMS=("com.samsung.tv.vnc-{}-1.armv7l.rpm")
        ;;
      rdp)
        OPTION_RPMS=("org.tizen.efreerdp-{}-1.armv7l.rpm")
        ;;
      knox)
        OPTION_RPMS=("com.samsung.tv.knox-browser-{}-1.armv7l.rpm")
        OPTION_RPMS+=("com.samsung.tv.knox-browser-autofill-{}-1.armv7l.rpm")
        OPTION_RPMS+=("com.samsung.tv.knox-browser-libs-{}-1.armv7l.rpm")
        OPTION_RPMS+=("com.samsung.tv.knox-browser-theme-resource-{}-1.armv7l.rpm")
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        echo "Unknown argument: $ARG" >&2
        usage
        exit 1
        ;;
    esac
  done
}

function install_rpms()
{
  for RPM_FILE in ${OPTION_RPMS[@]/'{}'/$OPTION_PKG_VERSION}; do
    # Get package name from RPM file name
    PKG_NAME=${RPM_FILE%-*-*}

    sdb -s "$OPTION_IP_ADDR" push "$OPTION_PKG_DIR/$RPM_FILE" /tmp

    sdb -s "$OPTION_IP_ADDR" shell rpm -e --nodeps "$PKG_NAME"
    sdb -s "$OPTION_IP_ADDR" shell tpk-backend --force-remove --preload -d "$PKG_NAME"
    sdb -s "$OPTION_IP_ADDR" shell rpm -ivh --force --nodeps "/tmp/$RPM_FILE"
    sdb -s "$OPTION_IP_ADDR" shell tpk-backend -y "$PKG_NAME" --preload
  done
}

parse_cmd $@

if [ -z "$OPTION_IP_ADDR" ]; then
  echo "IP address of the target not specified. Use -i=<addr>" >&2
  exit 1
fi

sdb connect "$OPTION_IP_ADDR"
sdb -s "$OPTION_IP_ADDR" root on

# Connect only
if [ -z "$OPTION_RPMS" ]; then
  exit 0
fi

if [ -z "$OPTION_PKG_VERSION" ]; then
  echo "Package version not specified. Use -v=<version>" >&2
  exit 1
fi

if [ ! -e "$HOME/.gbs.conf" ]; then
  echo "File $HOME/.gbs.conf not found" >&2
  exit 1
fi

BUILD_PROFILE=`sed -n 's/profile = profile.\(.*\)$/\1/p' "$HOME/.gbs.conf" | tr -d " "`
if [ -z "$OPTION_PKG_DIR" ]; then
  OPTION_PKG_DIR="$HOME/GBS-ROOT/local/repos/$BUILD_PROFILE/armv7l/RPMS"
fi

install_rpms
